cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.show_cart, name='show_cart'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('delete_from_main_cart/', views.delete_from_main_cart, name='delete_from_main_cart'),
    path('use_promo/', views.use_promo, name='use_promo'),
    path('sort_filter/', views.sort_filter, name='sort_filter'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('get_cart/', views.get_cart, name='get_cart'),
    path('delete_from_cart/', views.delete_from_cart, name='delete_from_cart'),
    path('wishlist_add/', views.wishlist_add, name='wishlist_add'),
    path('wishlist_delete/', views.wishlist_delete, name='wishlist_delete'),
    path('add_to_fav/', views.add_to_fav, name='add_to_fav'),




    # path('login/', views.login, name='login'),
    # path('logout/', views.logout_page, name='logout'),
    # path('profile/<nickname_req>', views.profile, name='profile'),
    # path('del_message/', views.del_message, name='del_message'),
    # path('bonus_pack/', views.bonus_pack, name='bonus_pack'),
    # path('about_us/', views.about_us, name='about_us'),
    # path('rules/', views.rules, name='rules'),
    # path('add_to_player_balance/', views.add_to_player_balance, name='add_to_player_balance'),
    # path('about_bonus_pack/', views.about_bonus_pack, name='about_bonus_pack'),




    # path('statistic/', views.statistic, name='statistic'),

]

ideaHome/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from page.views import customhandler404

# from page.views import customhandler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('item/', include('item.urls')),
    path('cart/', include('cart.urls')),
    path('user/', include('customuser.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = customhandler404

item/urls.py
from django.urls import path
from . import views

urlpatterns = [

]

order/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete
from customuser.models import User, Guest
from item.models import Item, PromoCode
from django.utils.safestring import mark_safe

class Wishlist(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                               verbose_name='Клиент')
    item = models.ForeignKey(Item, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Товар')

    def __str__(self):
        return 'Закладка клиента : %s ' % self.client.email

    class Meta:
        verbose_name = "Закладка клиента"
        verbose_name_plural = "Закладки клиентов"




class Order(models.Model):
    client = models.ForeignKey(User, blank=True, null=True, default=None, on_delete=models.CASCADE,
                               verbose_name='Заказ клиента')
    fio = models.CharField('ФИО', max_length=255, blank=True, null=True)
    email = models.CharField('Email', max_length=255, blank=True, null=True)
    phone = models.CharField('Телефон', max_length=255, blank=True, null=True)
    delivery = models.CharField('Тип доставки', max_length=255, blank=True, null=True)
    comment = models.TextField('Комментарий', blank=True, null=True)

    promo_code = models.ForeignKey(PromoCode, blank=True, null=True, default=None, on_delete=models.SET_NULL,
                              verbose_name='Использованный промо-код')
    total_price = models.IntegerField('Общая стоимость заказа', default=0)
    total_price_with_code = models.DecimalField('Общая стоимость заказа с учетом промо-кода', decimal_places=2,
                                                max_digits=10, default=0)
    track_code = models.CharField('Трек код', max_length=50, blank=True, null=True)
    order_code = models.CharField('Код заказа', max_length=10, blank=True, null=True)
    is_complete = models.BooleanField('Заказ выполнен ?', default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return 'Заказ № %s. Создан : %s  . Сумма заказа : %s' % (self.id, self.created_at.strftime('%d-%m-%Y'),  self.total_price)


    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def created_tag(self):

        return mark_safe('<strong>{}</strong>'.format(self.created_at.strftime('%d-%m-%Y, %H:%M:%S')))

    created_tag.short_description = mark_safe('<strong>Дaта заказа</strong>')

    def save(self, *args, **kwargs):
        if self.promo_code:
            self.total_price_with_code = self.total_price - (self.total_price * self.promo_code.promo_discount / 100)
        else:
            self.total_price_with_code = self.total_price
        super(Order, self).save(*args, **kwargs)




class ItemsInOrder(models.Model):
    order = models.ForeignKey(Order, blank=False, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='В заказе')
    item = models.ForeignKey(Item, blank=False, null=True, default=None, on_delete=models.CASCADE,
                              verbose_name='Товар')
    number = models.IntegerField('Кол-во', blank=True, null=True, default=0)
    current_price = models.IntegerField('Цена за ед.', default=0)
    total_price = models.IntegerField('Общая стоимость', default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.item.discount > 0:
            self.current_price = self.item.price - (self.item.price * self.item.discount / 100)
        else:
            self.current_price = self.item.price
        self.total_price = self.number * self.current_price

        super(ItemsInOrder, self).save(*args, **kwargs)


    def __str__(self):
        return 'Товар : %s . В заказе № %s .' % (self.item.name, self.order.id)

    class Meta:
        verbose_name = "Товар в заказе"
        verbose_name_plural = "Товары в заказе"

    def getfirstimage(self):
        url = None
        for img in self.item.itemimage_set.all():
            if img.is_main:
                url = img.image_small
        return url

    def image_tag(self):
        # used in the admin site model as a "thumbnail"
        if self.getfirstimage():
            return mark_safe('<img src="{}" width="100" height="100" />'.format(self.getfirstimage()))
        else:
            return mark_safe('<span>НЕТ МИНИАТЮРЫ</span>')

    def name_tag(self):
        name = self.item.name
        return name

    def article_tag(self):
        name = self.item.article
        return name

    article_tag.short_description = 'Артикул'
    name_tag.short_description = 'Название товара'
    image_tag.short_description = 'Основная картинка'


def ItemsInOrder_post_save(sender,instance,**kwargs):
    try:
        order = instance.order
    except:
        order = None

    if order:
        order_total_price = 0
        all_items_in_order = ItemsInOrder.objects.filter(order=order)

        for item in all_items_in_order:
            order_total_price += item.total_price

        instance.order.total_price = order_total_price
        instance.order.save(force_update=True)


post_delete.connect(ItemsInOrder_post_save, sender=ItemsInOrder)
post_save.connect(ItemsInOrder_post_save, sender=ItemsInOrder)

cart/views.py
import json

from django.shortcuts import render
from django.http import JsonResponse
from cart.models import Cart
from customuser.models import Guest
from item.models import PromoCode,Item,SubCategory
from datetime import datetime
from order.models import Wishlist


def format_number(num):
    if num % 1 == 0:
        return int(num)
    else:
        return num
def get_all_items(client=None,guest=None):
    all_cart_items = []
    if client:
        all_cart_items = Cart.objects.filter(client=client)
        print('Cart class : client cart items : ', all_cart_items)
    if guest:
        all_cart_items = Cart.objects.filter(guest=guest)
        print('Cart class : guest cart items : ', all_cart_items)
    if all_cart_items.exists():
        allitems = []
        for cartitem in all_cart_items:
            allitems.append({
                'id': cartitem.item.id,
                'name': cartitem.item.name,
                'num': cartitem.number,
                'price': cartitem.current_price,
                'image': cartitem.item.itemimage_set.first().image_small})
        return allitems

def show_cart(request):

    return render(request, 'page/cart.html', locals())

def wishlist_delete(request):
    return_dict = {}
    if request.user.is_authenticated:
        Wishlist.objects.get(id=int(request.POST.get('id'))).delete()

        return_dict['result'] = True
    else:
        return_dict['result'] = False
    return JsonResponse(return_dict)

def wishlist_add(request):
    return_dict = {}
    if request.user.is_authenticated:
        Wishlist.objects.create(client=request.user, item_id=int(request.POST.get('item_id')))

        return_dict['result'] = True
    else:
        return_dict['result'] = False
    return JsonResponse(return_dict)

def add_to_cart1(request):
    return_dict = {}
    data = request.POST
    print(data)
    s_key = request.session.session_key
    item_id = int(data.get('item_id'))
    item_number = int(data.get('item_number'))
    if request.user.is_authenticated:
        print('User is_authenticated')
        addtocart, created = Cart.objects.get_or_create(client=request.user,
                                                        item_id=item_id, defaults={'number': item_number})
        if not created:
            addtocart.number += int(item_number)
            addtocart.save(force_update=True)
        all_items_in_cart = Cart.objects.filter(client=request.user)

    else:
        print('User is_not authenticated')
        try:
            guest = Guest.objects.get(session=s_key)
            print('Guest already created')
        except:
            guest = None

        if not guest:
            guest = Guest.objects.create(session=s_key)
            guest.save()
            print('Guest created')

        addtocart, created = Cart.objects.get_or_create(guest=guest,
                                                           item_id=item_id, defaults={'number': item_number})
        if not created:
            addtocart.number += int(item_number)
            addtocart.save(force_update=True)

        all_items_in_cart = Cart.objects.filter(guest=guest)
    count_items_in_cart = all_items_in_cart.count()
    total_cart_price = 0

    return_dict['total_items_in_cart'] = count_items_in_cart
    return_dict['all_items'] = list()
    for item in all_items_in_cart:
        total_cart_price += item.total_price
        item_dict = dict()
        item_dict['id'] = item.item.id
        item_dict['name'] = item.item.name
        item_dict['name_slug'] = item.item.name_slug
        item_dict['price'] = item.current_price
        item_dict['total_price'] = item.total_price
        item_dict['number'] = item.number
        item_dict['image'] = item.item.itemimage_set.first().image_small
        return_dict['all_items'].append(item_dict)

    return_dict['total_cart_price'] = total_cart_price

    return JsonResponse(return_dict)

def delete_from_cart(request):
    return_dict = {}
    data = request.POST
    s_key = request.session.session_key
    item_id = int(data.get('item_id'))

    if request.user.is_authenticated:
        print('User is_authenticated')
        Cart.objects.filter(client=request.user, item_id=item_id).delete()
        all_items_in_cart = Cart.objects.filter(client=request.user)

    else:
        print('User is_not authenticated')

        guest = Guest.objects.get(session=s_key)
        Cart.objects.filter(guest=guest, item_id=item_id).delete()
        all_items_in_cart = Cart.objects.filter(guest=guest)
    count_items_in_cart = all_items_in_cart.count()
    total_cart_price = 0

    return_dict['total_items_in_cart'] = count_items_in_cart
    return_dict['all_items'] = list()
    for item in all_items_in_cart:
        total_cart_price += item.total_price
        item_dict = dict()
        item_dict['id'] = item.item.id
        item_dict['name'] = item.item.name
        item_dict['name_slug'] = item.item.name_slug
        item_dict['price'] = item.current_price
        item_dict['total_price'] = item.total_price
        item_dict['number'] = item.number
        item_dict['image'] = item.item.itemimage_set.first().image_small
        return_dict['all_items'].append(item_dict)

    return_dict['total_cart_price'] = total_cart_price
    return JsonResponse(return_dict)



def update_cart(request):
    return_dict = {}

    data = request.POST
    print(data)
    item_id = int(data.get('item_id'))
    item_number = int(data.get('item_number'))

    item = Cart.objects.get(id=item_id)
    item.number = item_number
    item.save(force_update=True)

    s_key = request.session.session_key

    if request.user.is_authenticated:
        print('update_cart : User is_authenticated')
        all_items_in_cart = Cart.objects.filter(client=request.user)
        used_promo = request.user.used_promo
        if not used_promo:
            promo_discount_value = 0

    else:
        print('update_cart : User is_not authenticated')

        guest = Guest.objects.get(session=s_key)
        all_items_in_cart = Cart.objects.filter(guest=guest)
        used_promo = guest.used_promo
        if not used_promo:
            promo_discount_value = 0

    count_items_in_cart = all_items_in_cart.count()
    total_cart_price = 0

    return_dict['total_items_in_cart'] = count_items_in_cart
    return_dict['all_items'] = list()
    for item in all_items_in_cart:
        total_cart_price += item.total_price
        item_dict = dict()
        item_dict['id'] = item.id
        item_dict['name'] = item.item.name
        item_dict['subcategory'] = item.item.subcategory.name
        item_dict['subcategory_slug'] = item.item.subcategory.name_slug
        item_dict['name_slug'] = item.item.name_slug
        item_dict['price'] = item.current_price
        item_dict['total_price'] = item.total_price
        item_dict['number'] = item.number
        item_dict['discount'] = item.item.discount

        item_dict['image'] = item.item.itemimage_set.first().image_small
        return_dict['all_items'].append(item_dict)
    total_cart_price_with_discount = total_cart_price
    if used_promo:
        print('with promo')
        promo_discount_value = used_promo.promo_discount
        total_cart_price_with_discount = format_number(
        total_cart_price - (total_cart_price * promo_discount_value / 100))


    return_dict['total_cart_price'] = total_cart_price
    return_dict['total_cart_price_with_discount'] = total_cart_price_with_discount
    return_dict['promo_discount_value'] = promo_discount_value

    return JsonResponse(return_dict)


def delete_from_main_cart(request):
    return_dict = {}

    data = request.POST
    print(data)
    item_id = int(data.get('item_id'))

    Cart.objects.get(id=item_id).delete()

    s_key = request.session.session_key

    if request.user.is_authenticated:
        print('delete_from_main_cart : User is_authenticated')
        all_items_in_cart = Cart.objects.filter(client=request.user)
        used_promo = request.user.used_promo
        if all_items_in_cart.count() == 0:
            request.user.used_promo = None
            promo_discount_value = 0
            used_promo = None
            request.user.save(force_update=True)
        if not used_promo:
            promo_discount_value = 0

    else:
        print('delete_from_main_cart : User is_not authenticated')

        guest = Guest.objects.get(session=s_key)
        all_items_in_cart = Cart.objects.filter(guest=guest)
        used_promo = guest.used_promo

        if all_items_in_cart.count() == 0:
            guest.used_promo = None
            promo_discount_value = 0
            used_promo = None
            guest.save(force_update=True)
        if not used_promo:
            promo_discount_value = 0
    count_items_in_cart = all_items_in_cart.count()
    total_cart_price = 0

    return_dict['total_items_in_cart'] = count_items_in_cart
    return_dict['all_items'] = list()
    for item in all_items_in_cart:
        total_cart_price += item.total_price
        item_dict = dict()
        item_dict['id'] = item.id
        item_dict['name'] = item.item.name
        item_dict['subcategory'] = item.item.subcategory.name
        item_dict['subcategory_slug'] = item.item.subcategory.name_slug
        item_dict['name_slug'] = item.item.name_slug
        item_dict['price'] = item.current_price
        item_dict['total_price'] = item.total_price
        item_dict['number'] = item.number
        item_dict['discount'] = item.item.discount

        item_dict['image'] = item.item.itemimage_set.first().image_small
        return_dict['all_items'].append(item_dict)

    return_dict['total_cart_price'] = total_cart_price
    total_cart_price_with_discount = total_cart_price
    if used_promo:
        print('with promo')
        promo_discount_value = used_promo.promo_discount
        total_cart_price_with_discount = format_number(
        total_cart_price - (total_cart_price * promo_discount_value / 100))

item/views.py
from django.shortcuts import render
from django.http import JsonResponse, Http404
from item.models import Item,ItemImage
from cart.models import Cart
from customuser.models import User, Guest

templates/page/_cb-form.html
<div class="shadow-box">
    <div class="shadow-box-inner">
        <h5 class="mb-40">Хотите узнать подробнее
            <span>или убедиться в качестве?</span>
        </h5>
        <form action="{% url 'send_cb' %}" method="post">{% csrf_token %}
              <input class="form-control input mb-10" required type="text" id="form_name" name="name" placeholder="Как к Вам обращаться?">
        <input id="form_phone" required class="form-control input masked-phone mb-30" name="phone"
                placeholder="Ваш сотовый номер" v-maska="['+7 (###) ##-##-##', '+7 (###) ###-##-##']" />
            <input style="display: none" type="checkbox" name="agree">
            <textarea style="display: none" name="comment"></textarea>
        <button type="submit" class="btn mb-40">Перезвоните мне</button>

        <p class="form-agreed-text">Нажимая на кнопку, вы принимаете <a href="#">условия передачи данных</a></p>

        <input style="display: none" name="agree" type="checkbox">
        </form>

    </div>
</div>

templates/page/_item-card.html
<div class="catalog-item">
    {% if item.discount > 0 %}
        <span class="catalog-item-discount">- {{ item.discount }}%</span>
    {% endif %}
 {% if request.user.is_authenticated %}
   <a  href="#" class="catalog-item-fav-btn "
       @click.prevent="addInFav"></span>
       <i data-id="{{ item.id }}" class="fa {% if item.id in wishlist_ids %}fa-heart{% else %}fa-heart-o{% endif %}"></i></a>
{% endif %}
    <a class="catalog-item-image" href="{{ item.get_absolute_url }}">
        <img src="{{ item.get_small_image }}" alt="{{ item.name }}">
    </a>
    <a class="catalog-item-info" href="{{ item.get_absolute_url }}">
        <p>{{ item.name }}</p>

        <span>Артикул: {{ item.article }}</span>
        <span>Ед. измерения: {{ item.units }}</span>
        <span>Производитель: {{ item.manufactor.name }}</span>

    </a>
    <div class="item-info-price-wrapper">
        {% if item.discount > 0 %}
            <p class="current-price"><span id="current_price">{{ item.discount_value }}</span> <i class="fa fa-rub"></i></p>
            <p class="old-price">{{ item.price }} <i class="fa fa-rub"></i></p>
        {% else %}
            <p class="current-price"><span id="current_price">{{ item.price }}</span> <i class="fa fa-rub"></i></p>

        {% endif %}
    </div>
    {% if item.id in cart_items_ids %}
        <button id="add_btn_{{ item.id }}" data-id="{{ item.id }}" data-name="{{ item.name }}" data-price="{{ item.discount_value }}" data-image="{{ item.itemimage_set.first.image_small }}" @click="addItem" class="btn catalog-item-btn" disabled="disabled">в корзине</button>

    {% else %}
        <button id="add_btn_{{ item.id }}" data-id="{{ item.id }}" data-name="{{ item.name }}" data-price="{{ item.discount_value }}" data-image="{{ item.itemimage_set.first.image_small }}" @click="addItem" class="btn catalog-item-btn">в корзину</button>

    {% endif %}
    {#                            <p class="catalog-item-price">{{ item.price }} <i class="fa fa-rub"></i></p>#}
    {% if request.user.is_superuser %}
        <a target="_blank" style="font-weight: bold;color: red" href="/admin/item/item/{{ item.id }}/change/">редакировать</a>
    {% endif %}
</div><!--//catalog-item-->

templates/page/about.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}

  <div class="main">
    <div class="breadcrumbs bg-grey">
        <div class="container ">
            <ul>
                <li><a href="#">Главная</a></li>

                <li><span>О МАГАЗИНЕ</span></li>
            </ul>
        </div>
    </div>
    <section class="about ">
        <div class="container">
            <div class="section-header"><h1>{{ pageH1 }}</h1></div>
            <p>Компания «Идеи для дома» представлена на рынке отделочных материалов с 2007 года. За это время «Идеи для дома»
                зарекомендовали себя как надежный поставщик отделочных материалов и декоративных элементов.</p>
            <p><strong>Основная цель нашей работы</strong> – предоставление высококачественных материалов, а также максимально квалифицированной информации об их использовании.</p>
            <p>Мы работаем со следующими проверенными производителями декоративных отделочных материалов: <br>
            <ul>
                <li><i class="fa fa-check-circle-o"></i>Decor-dizayn</li>
                <li><i class="fa fa-check-circle-o"></i>Европласт</li>
                <li><i class="fa fa-check-circle-o"></i>Перфект</li>
                <li><i class="fa fa-check-circle-o"></i>Каметерра</li>
                <li><i class="fa fa-check-circle-o"></i>Оникс</li>
                <li><i class="fa fa-check-circle-o"></i>АртШтайн</li>
                <li><i class="fa fa-check-circle-o"></i>Камелот и др.</li>

            </ul>
            </p>
            <p>Мы непрерывно увеличиваем ассортимент продукции, самые востребованные позиции стараемся всегда иметь в наличии. Мы предоставляем большой выбор товаров для создания современной обстановки в любом помещении – офисе, квартире, загородном доме и любом другом объекте.</p>
            <p><strong>Наши основные клиенты</strong> – это строительные фирмы, отделочные бригады и частные лица. Большинство товаров мы имеем в наличии и быстро доставляем по нужному адресу, если же вы заказали товар, которого нет в наличии – то мы обозначим сроки поставки, которые всегда неукоснительно соблюдаем.</p>
            <div class="section-header color-red"><h2>Нас отличает:</h2></div>
            <div class="about-row">
                <img src="img/about1.png" alt="">
                <p><strong>Стремление к постоянному росту и развитию.</strong> Мы непрерывно расширяем ассортимент материалов, учитывая потребности клиентов и предлагая оптимальные цены.</p>
            </div>
            <div class="about-row">
                <img src="img/about2.png" alt="">
                <p><strong>Чистота сделок, хорошая репутация и отзывы клиентов.</strong> Мы исполняем все обязательства перед клиентами, соблюдаем положенные нормы и предоставляем гарантии.</p>
            </div>
            <div class="about-row">
                <img src="img/about3.png" alt="">
                <p><strong>Высокое качество продукции.</strong> Мы выбираем для реализации лишь те товары, которые способны максимально отвечать потребностям наших клиентов. Мы исправно соблюдаем все сроки и внимательно перепроверяем все товары перед отправкой клиенту – это обеспечивает отсутствие претензий со стороны пользователей. Заказав товар у нас, люди становятся нашими постоянными покупателями.</p>
            </div>
            <div class="about-row">
                <img src="img/about4.png" alt="">
                <p><strong>Сплоченный коллектив. </strong> За годы работы на рынке мы смогли собрать сильную команду – каждый сотрудник непременно помогает не только клиентам, но и своим коллегам.</p>
            </div>
            <div class="about-contacts">
                <div class="section-header color-red"><h2>Уважаемые покупатели!</h2></div>
                <p>Ознакомиться с ассортиментом, представленным на сайте, можно в одном из наших магазинов, которые находятся по адресам:</p>
                <p>ТК "ЧЕЛСИ" Троицкий тракт, 21, корпус 2 / сектор 16<br>
                    Тел. +7 (351) 215 55 07, сот.8 908 583 40 15<br>
                    ТК "ЧЕЛСИ-2" Новоградский проспект, 64<br>
                    Тел. +7 (351) 222 88 88 (доб.1520), сот. 8 951 782 92 74<br>
                    Тел. 8 900 071 06 56 Тел. 8 982 333 7 888 (многоканальный)</p><br>
{#                <a style="display: block" class="mb-20" href="">Открыть схему проезда</a>#}
                <p>Задать вопросы вы можете по телефону <a href="tel:89823337888">8 (982) 333 7888</a> или написать на почту <a href="mailto:ideahome@mail.ru">ideahome@mail.ru</a>.
                    Также вы можете возпользоваться функцией <a href="#" onclick="">заказа звонка</a>, оставьте свой номер и мы свяжемся с вами в ближайшее время!</p>
            </div>
        </div><!--//container-->

    </section>
</div><!--//main-->

{% endblock %}

templates/page/catalog.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}

    <div class="main">
        <div class="breadcrumbs bg-grey">
            <div class="container ">
                <ul>
                    <li><a href="/">Главная</a></li>

                    <li><span>КАТАЛОГ</span></li>
                </ul>
            </div>
        </div>
        <section class="manufactors">
            <div class="container">
               <div class="section-header"><h1>{{ pageH1 }}</h1></div>

                <div style="grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));"  class="manufactors-wrapper ">
                    {% for cat in all_categories %}
                    <div class="manufactors-item">
                        <a href="{% url 'category' cat.name_slug %}">
                            <div class="manufactors-item-inner">

                                    <img src="{{ cat.image.url }}" alt="">
                                <p>{{ cat.name }}</p>


                            </div>
                        </a>
                    </div><!--//manufactors-item-->
                  {% endfor %}

                </div><!--//manufactors-wrapper-->


            </div><!--//container-->

        </section>
    </div><!--//main-->

{% endblock %}

templates/page/manufacturers.html
{% extends 'basic.html' %}
{% load static %}
{% block content %}

    <div class="main">
        <div class="breadcrumbs bg-grey">
            <div class="container ">
                <ul>
                    <li><a href="/">Главная</a></li>

                    <li><span>Производители</span></li>
                </ul>
            </div>
        </div>
        <section class="manufactors">
            <div class="container">
               <div class="section-header"><h1>{{ pageH1 }}</h1></div>
                <p class="mb-20">Выберите производителя и посмотрите продукцию, которую вы можете приобрести у нас</p>
                <div class="manufactors-wrapper">
                    {% for manufactor in all_manufacturers %}
                    <div class="manufactors-item">
                        <a href="{% url 'manufactor' manufactor.name_slug %}">
                            <div class="manufactors-item-inner">
                                <img src="{{ manufactor.image.url }}" alt="">
                                <p class="manufactors-item__name">{{ manufactor.name }}</p>
                            </div>
                        </a>
                    </div><!--//manufactors-item-->
                  {% endfor %}

                </div><!--//manufactors-wrapper-->


            </div><!--//container-->

        </section>
    </div><!--//main-->

{% endblock %}

templates/page/order_complete.html
{% extends 'basic.html' %}
{% load static %}

{% block content %}


<div class=" main">
   <div class="breadcrumbs bg-grey mb-40">
            <div class="container ">
                <ul>
                    <li><a href="/">Главная</a></li>

                    <li><span>Вход</span></li>
                </ul>
            </div>
        </div>
    <!--/.row-->

<section>
    <div class="container">
        <div class="section-header text-center">

                    <h1>Спасибо за Ваш заказ.</h1>


                </div>
    <p class=" text-center "> <b>Вся информация о заказе и его статусе оправлена Вам на указанный адрес электронной почты.</b> </p>
    <p class=" text-center mb-40"><b>С Вами свяжется наш менеджер для уточнения заказа.</b> </p>
         <div class="cartContent ">
                        <table style="width:100%" class="cartTable cartTableBorder">
                            <tbody>

                            <tr class="CartProduct  cartTableHeader">
                                <td colspan="2"> Вы заказали</td>


                                <td style="width:15%"></td>
                            </tr>
                               {% for item in order.itemsinorder_set.all %}

                                     <tr class="CartProduct">
                                <td class="CartProductThumb">

                                       <div> <img style="width: 250px;" alt="img"

                                                               src="{{ item.item.get_small_image }}">


                                                </div>
                                </td>
                                <td>
                                    <div class="CartDescription">
                                         <h4><a href="#"> {{ item.item.name }} </a></h4>


                                       {% if item.item.discount > 0 %}

                                                        <div class="price" style="padding-bottom: 5px;">
                                                         <span style="font-size: 20px;">
                                                             <span>{{ item.item.discount_value }} &#8381;</span>
                                                             <span class="old-price">{{ item.item.price }} &#8381;</span>
                                                         </span>
                                                        </div>
                                                    {% else %}
                                                        <div class="price" style="padding-bottom: 5px;"><span style="font-size: 20px;">{{ item.item.price }} &#8381;</span></div>
                                                    {% endif %}
                                    </div>
                                </td>


                                <td class="price">{{ item.total_price }} &#8381;</td>
                            </tr>

                                        {% endfor %}




                            </tbody>
                        </table>
                    </div>
    </div>
</section>

</div>





{% endblock %}